#!/bin/bash
set -e

echo ""
echo "  ____                            _   "
echo " / ___|  ___  __ _ _ __   ___  _ __| |_ "
echo " \\___ \\ / _ \\/ _\` | '_ \\ / _ \\| '__| __|"
echo "  ___) |  __/ (_| | |_) | (_) | |  | |_ "
echo " |____/ \\___|\\__,_| .__/ \\___/|_|   \\__|"
echo "                  |_|                    "
echo ""
echo " The Org OS for VPS — deploy in 60 seconds"
echo ""

# Check Docker
if ! command -v docker &> /dev/null; then
  echo "Error: Docker is required. Install it first: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &> /dev/null; then
  echo "Error: Docker Compose v2 is required."
  exit 1
fi

# Question 1: Domain
read -p "What's your domain? (e.g., seaport.example.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
  echo "Domain is required."
  exit 1
fi

# Question 2: Platform name (optional)
read -p "What do you want to call your platform? [Seaport]: " APP_NAME
APP_NAME=${APP_NAME:-Seaport}

# Auto-generate secrets
DB_PASSWORD=$(openssl rand -hex 24)
SESSION_SECRET=$(openssl rand -hex 32)

# Detect protocol
if [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
  SITE_URL="https://$DOMAIN"
else
  SITE_URL="http://$DOMAIN"
fi

# Write .env
cat > .env << EOF
# Generated by deploy.sh on $(date)
DB_PASSWORD=$DB_PASSWORD
SESSION_SECRET=$SESSION_SECRET
SITE_URL=$SITE_URL
PORT=3000
APP_NAME=$APP_NAME
EOF

echo ""
echo "Generated .env with secure credentials."
echo ""

# Write Nginx reverse proxy config
NGINX_CONF="/etc/nginx/sites-available/seaport"
if command -v nginx &> /dev/null; then
  echo "Configuring Nginx reverse proxy..."
  sudo tee "$NGINX_CONF" > /dev/null << NGINX
server {
    listen 80;
    server_name $DOMAIN;

    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX
  sudo ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/seaport
  sudo nginx -t && sudo systemctl reload nginx
  echo "Nginx configured: $DOMAIN → localhost:3000"
else
  echo "Note: Nginx not found. Install it for reverse proxy + SSL:"
  echo "  sudo apt install nginx"
  echo "  Then re-run ./deploy.sh or manually proxy port 3000."
fi

echo ""

# Start containers
echo "Starting Seaport..."
docker compose up -d --build

echo ""
echo "============================================"
echo "  Seaport is running!"
echo "============================================"
echo ""
echo "  Visit: $SITE_URL"
echo "  The first visit will show the setup wizard."
echo ""
echo "  Platform name: $APP_NAME"
echo ""

# Offer SSL setup
if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
  echo ""
  read -p "Set up free SSL with Let's Encrypt? (y/N): " SETUP_SSL
  if [[ "$SETUP_SSL" =~ ^[Yy]$ ]]; then
    if command -v certbot &> /dev/null; then
      sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email
      # Update SITE_URL to https
      sed -i "s|SITE_URL=http://$DOMAIN|SITE_URL=https://$DOMAIN|" .env
      docker compose restart seaport
      echo "SSL configured! Visit: https://$DOMAIN"
    else
      echo "Install certbot first: sudo apt install certbot python3-certbot-nginx"
    fi
  fi
fi

echo ""
echo "Useful commands:"
echo "  docker compose logs -f        # View logs"
echo "  docker compose down           # Stop"
echo "  docker compose up -d          # Start"
echo "  docker compose up -d --build  # Rebuild after updates"
echo ""
