[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx drizzle-kit push --force --dialect postgresql --schema ./server/db/schema/index.ts --url \"$DATABASE_URL\" && node dist/server/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
